version : '3.8'

services:
  web:
    build: ./services/web
    command: flask run --host 0.0.0.0 --no-reload
    volumes:
      - ./services/web/:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=newPassword
      - POSTGRES_DB=postgres

volumes:
  postgres_data: